services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/cinecrew
      - JWT_SECRET=change_me_super_secret
      - PORT=5000
      - CLIENT_BASE_URL=http://localhost:8081
    ports:
      - "5000:5000"
    depends_on:
      - mongo
volumes:
  mongo_data:
